# Production values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: vasanthagokul/dotnet-print-appsettings
  pullPolicy: Always
  tag: latest

configMap:
  Environment: "production-k8s-cluster"
  Database__ConnectionString: "connection string from prod values yaml"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi