{{- if .Values.secret }}
apiVersion: v1
kind: secret
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.secret | nindent 2 }}
{{- end }}